# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cushion', models.CharField(max_length=255)),
                ('faucet', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
